# Generated by Django 4.2.16 on 2024-11-24 19:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\KBTU\\7 semester\\BackEnd-For-High-Load-Applications\\Assigment4\\file_loader\\secure_uploads'), upload_to=''),
        ),
    ]
