version: '3.9'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis:alpine
    container_name: assigment4-redis
    ports:
      - "6379:6379"

  celery-default-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker -l info -Q default -n default
    env_file:
      - .env
    depends_on:
      - web
      - redis
    deploy:
      restart_policy:
        condition: on-failure
  celery-email-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker -l info -Q emails -n emails
    env_file:
      - .env
    depends_on:
      - web
      - redis
    deploy:
      restart_policy:
        condition: on-failure
  flower:
    image: mher/flower:latest
    build:
      dockerfile: Dockerfile
    command: celery -A config flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - web
      - redis
    env_file:
      - .env
  locust:
    build:
      context: ./locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/locust
    command: >
      locust -f /locust/locustfile.py
      --host=http://web:8000
    depends_on:
      - web