global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['web1:8000', 'web2:8000', 'web2:8000']

  - job_name: 'postgres'
    static_configs:
        - targets: [ 'postgres_exporter:9187' ]